- name: certificates
  src: https://github.com/ksylvan/docker-mail-server/tree/develop/roles/certificates
  version: origin/develop

- name: deploy-user
  src: https://github.com/ksylvan/docker-mail-server/tree/develop/roles/deploy-user
  version: origin/develop

- name: docker
  src: https://github.com/ksylvan/docker-mail-server/tree/develop/roles/docker
  version: origin/develop

- name: mailserver
  src: https://github.com/ksylvan/docker-mail-server/tree/develop/roles/mailserver
  version: origin/develop

- name: secure-server
  src: https://github.com/ksylvan/docker-mail-server/tree/develop/roles/secure-server
  version: origin/develop

- name: certificates
  src: https://github.com/ksylvan/docker-mail-server/tree/develop/roles/unblock-ports
  version: origin/develop